# Generated by Django 5.2.1 on 2025-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='article',
            field=models.CharField(default='9edb1a79', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
