# Generated by Django 5.2.1 on 2025-05-30 14:52

import ad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_ad_article'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='ad_ad_article_7356bd_idx',
        ),
        migrations.AlterField(
            model_name='ad',
            name='article',
            field=models.CharField(default=ad.models.generate_article, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
