# Generated by Django 5.2.1 on 2025-06-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_remove_ad_ad_ad_article_7356bd_idx_alter_ad_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='slug',
        ),
    ]
